# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"app": "app.ipynb",
         "hello": "app.ipynb",
         "migrate": "app.ipynb",
         "DB": "db.ipynb",
         "evolve_ignore": "db.ipynb",
         "prefixed_snake_case": "db.ipynb",
         "BaseModel": "db.ipynb",
         "EVOLVE_IGNORE_TABLES": "db.ipynb",
         "League": "understat.ipynb",
         "Season": "db.ipynb",
         "Matches": "db.ipynb",
         "fetch_html": "understat.ipynb",
         "extract_json": "understat.ipynb",
         "Understat": "understat.ipynb"}

modules = ["app.py",
           "db.py",
           "understat.py"]

doc_url = "https://torvaney.github.io/understatdb/"

git_url = "https://github.com/torvaney/understatdb/tree/master/"

def custom_doc_links(name): return None
