# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"app": "00_app.ipynb",
         "hello": "00_app.ipynb",
         "fetch_html": "understat.ipynb",
         "extract_json": "understat.ipynb",
         "League": "understat.ipynb",
         "Understat": "understat.ipynb"}

modules = ["core.py",
           "understat.py"]

doc_url = "https://torvaney.github.io/understatdb/"

git_url = "https://github.com/torvaney/understatdb/tree/master/"

def custom_doc_links(name): return None
