# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/db.ipynb (unless otherwise specified).

__all__ = ['DB', 'evolve_ignore', 'prefixed_snake_case', 'BaseModel']

# Cell
import functools

import peewee
import playhouse.postgres_ext


DB = peewee.DatabaseProxy()

# Cell

_EVOLVE_IGNORE_TABLES = []


def evolve_ignore(cls, registry=_EVOLVE_IGNORE_TABLES):
    registry.append(cls._meta.table_name)
    return cls


def prefixed_snake_case(prefix, cls):
    return prefix + peewee.make_snake_case(cls.__name__)


@evolve_ignore
class BaseModel(peewee.Model):
    """
    A model for base (json) data from Understat
    """
    class Meta:
        database = DB
        legacy_table_names = False
        table_function = functools.partial(prefixed_snake_case, 'base_')