# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_app.ipynb (unless otherwise specified).

__all__ = ['app', 'hello']

# Cell
import typer


app = typer.Typer()

# Cell
@app.command()
def hello(name: str):
    typer.echo(f"Hello, {name}!")

# Cell
try:
    # Try/except block seems to be the 'canonical'
    # way to export __name__ == __main__ in nbdev.
    # By excepting an ImportError, we don't have to
    # include nbdev as a runtime dependency (only a
    # development dependency).
    #
    # See:
    #  * https://pete88b.github.io/fastpages/nbdev/fastai/jupyter/2020/07/24/nbdev-deep-dive.html#Export-a-if-__name__-==-
    #  * https://forums.fast.ai/t/nbdev-is-there-a-way-to-export-a-if-name-main-clause/73050/3
    from nbdev.imports import IN_NOTEBOOK
except ImportError:
    IN_NOTEBOOK = False

if __name__ == '__main__' and not IN_NOTEBOOK:
    app()